export const skills = {
  javascript: { imgSrc: "imgs/icon/javascript.png", skillName: "JavaScript" },
  typescript: { imgSrc: "imgs/icon/typescript.png", skillName: "typescript"},
  html: { imgSrc:"imgs/icon/html.png",skillName:"html"},
  css: { imgSrc:"imgs/icon/css.png",skillName:"css"},
  react: { imgSrc:"imgs/icon/react.png",skillName:"react"},
  styledComponents: { imgSrc:"imgs/icon/styled-components.png",skillName:"styled-components"},
  reactRouter: { imgSrc:"imgs/icon/react-router.png",skillName:"react-router"},
  firebase: { imgSrc:"imgs/icon/firebase.png",skillName:"firebase"},
  bootstrap: { imgSrc:"imgs/icon/bootstrap.png",skillName:"bootstrap"},
  tailwind: { imgSrc:"imgs/icon/tailwind.png",skillName:"tailwind"},
  redux: { imgSrc:"imgs/icon/redux.png",skillName:"redux"},
  github: { imgSrc:"imgs/icon/github.png",skillName:"github"},
  sass: { imgSrc:"imgs/icon/sass.png",skillName:"sass"},
};
